# Generated by Django 3.2.23 on 2024-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientmodel',
            name='apartment',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='recipientmodel',
            name='build',
            field=models.CharField(blank=True, choices=[('', ''), ('3', '3'), ('5', '5'), ('7', '7'), ('9', '9'), ('11', '11'), ('13', '13'), ('15', '15'), ('17', '17'), ('20', '20'), ('25', '25'), ('27', '27'), ('73', '73'), ('75', '75'), ('77', '77'), ('81', '81'), ('85', '85'), ('87', '87'), ('89', '89'), ('91', '91'), ('93', '93'), ('99', '99'), ('101', '101'), ('103', '103'), ('105', '105'), ('107', '107'), ('111', '111'), ('115', '115'), ('117', '117'), ('123', '123'), ('127', '127'), ('133', '133')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='recipientmodel',
            name='build_letter',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'А'), ('B', 'Б'), ('V', 'В'), ('G1', 'Г'), ('D', 'Д'), ('E1', 'Е'), ('E2', 'Є'), ('G2', 'Ж')], default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='recipientmodel',
            name='street',
            field=models.CharField(choices=[('STR', 'Стрийська'), ('MKL', 'Мікльоша'), ('SOK', 'Сокільницька')], default='STR', max_length=3),
        ),
    ]
