# Generated by Django 3.2.23 on 2024-01-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20240124_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientmodel',
            name='recipient_name',
        ),
        migrations.DeleteModel(
            name='LetterCardModel',
        ),
        migrations.DeleteModel(
            name='SenderModel',
        ),
    ]
