# Generated by Django 3.2.23 on 2024-01-29 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_letteritemmodel_expired_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letteritemmodel',
            options={'ordering': ['-date_of_receipt'], 'verbose_name': 'letter', 'verbose_name_plural': 'Letters'},
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 29, 15, 27, 13, 221612)),
        ),
    ]
