# Generated by Django 3.2.23 on 2024-01-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteritemmodel',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.recipientmodel'),
            preserve_default=False,
        ),
    ]
