# Generated by Django 3.2.23 on 2024-02-01 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20240201_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 1, 8, 20, 27, 860442, tzinfo=utc)),
        ),
    ]
