# Generated by Django 3.2.23 on 2024-02-06 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20240202_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letteritemmodel',
            name='letter_image',
        ),
        migrations.AddField(
            model_name='letteritemmodel',
            name='letter_image_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='letteritemmodel',
            name='letter_image_url',
            field=models.CharField(blank=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 6, 9, 1, 12, 301297, tzinfo=utc)),
        ),
    ]
