# Generated by Django 3.2.23 on 2024-02-13 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_letteritemmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 7, 55, 9, 807783, tzinfo=utc)),
        ),
    ]
