# Generated by Django 3.2.23 on 2024-02-13 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20240213_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitemmodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_mails', to='dashboard.recipientmodel'),
        ),
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 19, 25, 38, 602082, tzinfo=utc)),
        ),
    ]
