# Generated by Django 3.2.23 on 2024-02-17 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20240213_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailitemmodel',
            options={'ordering': ['date_of_receipt'], 'verbose_name': 'letter', 'verbose_name_plural': 'Letters'},
        ),
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 17, 5, 36, 28, 146991, tzinfo=utc)),
        ),
    ]
