# Generated by Django 3.2.23 on 2024-03-07 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20240307_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 10, 28, 37, 922687, tzinfo=utc)),
        ),
    ]
