# Generated by Django 3.2.23 on 2024-03-10 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20240307_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitemmodel',
            name='date_of_receipt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 10, 13, 58, 39, 783152, tzinfo=utc)),
        ),
    ]
