# Generated by Django 3.2.23 on 2024-03-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20240316_0931'),
        ('dashboard', '0025_auto_20240316_1245'),
    ]

    operations = [
    ]
