# Generated by Django 3.2.23 on 2024-01-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(choices=[('STR', 'Стрийська'), ('MKL', 'Мікльоша'), ('SOK', 'Сокільницька')], default='STR', max_length=3)),
                ('build', models.CharField(blank=True, choices=[('', ''), ('3', '3'), ('5', '5'), ('7', '7'), ('9', '9'), ('11', '11'), ('13', '13'), ('15', '15'), ('17', '17'), ('20', '20'), ('25', '25'), ('27', '27'), ('73', '73'), ('75', '75'), ('77', '77'), ('81', '81'), ('85', '85'), ('87', '87'), ('89', '89'), ('91', '91'), ('93', '93'), ('99', '99'), ('101', '101'), ('103', '103'), ('105', '105'), ('107', '107'), ('111', '111'), ('115', '115'), ('117', '117'), ('123', '123'), ('127', '127'), ('133', '133'), ('260', '260'), ('262', '262'), ('264', '264'), ('266', '266'), ('268', '268'), ('270', '270'), ('272', '272'), ('274', '274'), ('276', '276'), ('278', '278'), ('280', '280'), ('282', '282'), ('284', '284'), ('286', '286'), ('288', '288'), ('290', '290'), ('292', '292'), ('294', '294'), ('296', '296'), ('298', '298'), ('300', '300'), ('302', '302'), ('304', '304'), ('306', '306'), ('308', '308'), ('310', '310'), ('312', '312'), ('314', '314'), ('316', '316'), ('318', '318'), ('320', '320'), ('322', '322'), ('324', '324'), ('326', '326'), ('328', '328'), ('330', '330')], default='', max_length=3)),
                ('build_letter', models.CharField(blank=True, choices=[('', ''), ('A', 'А'), ('B', 'Б'), ('V', 'В'), ('G1', 'Г'), ('D', 'Д'), ('E1', 'Е'), ('E2', 'Є'), ('G2', 'Ж')], default='', max_length=2, null=True)),
                ('apartment', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='LetterItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13)),
                ('slug', models.SlugField(blank=True, max_length=13, unique=True)),
                ('is_court', models.BooleanField(default=False)),
                ('is_court_subpoena', models.BooleanField(default=False)),
                ('is_police_subpoena', models.BooleanField(default=False)),
                ('date_of_receipt', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.recipientmodel')),
            ],
            options={
                'verbose_name': 'letter',
                'verbose_name_plural': 'Letters',
            },
        ),
    ]
