# Generated by Django 3.2.23 on 2024-01-27 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
