# Generated by Django 3.2.23 on 2024-02-01 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240129_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letteritemmodel',
            old_name='is_police_subpoena',
            new_name='is_police_fine',
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 1, 5, 55, 36, 700357, tzinfo=utc)),
        ),
    ]
