# Generated by Django 3.2.23 on 2024-02-08 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20240206_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letteritemmodel',
            name='letter_image_url',
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 8, 14, 44, 20, 47150, tzinfo=utc)),
        ),
    ]
