# Generated by Django 3.2.23 on 2024-02-11 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20240208_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='letteritemmodel',
            name='marks',
            field=models.CharField(choices=[('', ''), ('COURT', 'Суд'), ('CRTSU', 'Судова повістка'), ('PFINE', 'Поліцейський штраф')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 11, 5, 45, 2, 441567, tzinfo=utc)),
        ),
    ]
