# Generated by Django 3.2.23 on 2024-02-11 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20240211_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letteritemmodel',
            name='marks',
        ),
        migrations.AlterField(
            model_name='letteritemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 11, 15, 51, 9, 453972, tzinfo=utc)),
        ),
    ]
