# Generated by Django 3.2.23 on 2024-02-13 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_letteritemmodel_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13)),
                ('slug', models.SlugField(blank=True, max_length=13, unique=True)),
                ('is_court', models.BooleanField(default=False)),
                ('is_court_subpoena', models.BooleanField(default=False)),
                ('is_police_fine', models.BooleanField(default=False)),
                ('letter_image_id', models.CharField(blank=True, max_length=40)),
                ('date_of_receipt', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 8, 4, 29, 164792, tzinfo=utc))),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.recipientmodel')),
            ],
            options={
                'verbose_name': 'letter',
                'verbose_name_plural': 'Letters',
                'ordering': ['-date_of_receipt'],
            },
        ),
        migrations.DeleteModel(
            name='LetterItemModel',
        ),
    ]
