# Generated by Django 3.2.23 on 2024-02-22 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20240217_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipientmodel',
            options={'ordering': ['-id'], 'verbose_name': 'recipient', 'verbose_name_plural': 'Recipients'},
        ),
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 22, 5, 35, 59, 442496, tzinfo=utc)),
        ),
    ]
