# Generated by Django 3.2.23 on 2024-02-24 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20240222_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailitemmodel',
            name='re_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 24, 9, 17, 7, 672925, tzinfo=utc)),
        ),
    ]
