# Generated by Django 3.2.23 on 2024-03-02 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_mailitemmodel_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailitemmodel',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 2, 5, 48, 4, 152275, tzinfo=utc)),
        ),
    ]
